Bug #1993439 - Changing search depth and output to mount scripts if needed via ConfigMap
sclorg/httpd-container pull request #121
Opened 2021-08-16 11:34 UTC by sreber84

RHBZ #1993439 changing search to make sure we find files mounted from a ConfigMap or in sub-directories to consider them as well and run them according the process_extending_files() function. That will allow users to mount custom scripts in Kubernetes via ConfigMap and thus prevent specific builds to add the necessary scripts.

2021-08-16 11:36 UTC, sreber84 commented
This is in relation to issue #118  as well as #117 to allow loading scripts using a `ConfigMap` and then execute logic as intended, without the need of running a specific build.

2021-08-16 14:44 UTC, sreber84 commented
[test]

2021-09-27 06:05 UTC, sreber84 commented
@phracek are you able to review this case ?

2021-11-08 13:37 UTC, phracek commented
[test-all]

2021-11-09 08:28 UTC, phracek commented
[test-openshift-4]

2021-11-09 11:23 UTC, phracek requested changes
@sreber84 Can you please explain your changes a bit more?

2021-11-09 11:26 UTC, phracek commented on 2.4/root/usr/share/container-scripts/httpd/common.sh
> +  [ -d "$custom_dir" ] && find "$custom_dir" -maxdepth 5 -type f -name "$files_matched" -printf "%p\n"
What about using some recursive approach instead of increasing maxdepth?

2021-11-25 12:17 UTC, sreber84 commented on 2.4/root/usr/share/container-scripts/httpd/common.sh
> +  [ -d "$custom_dir" ] && find "$custom_dir" -maxdepth 5 -type f -name "$files_matched" -printf "%p\n"
I validated certain changes and found this most feasible as it it does not change the code too much and helps to overcome the fact that we need to look into sub directories when mounting a `ConfigMap` or `secret` with the data. But I can certainly also check for a more feasible approach that takes recursive search into consideration.

2022-02-01 13:15 UTC, phracek commented
[test-openshift]

2022-02-01 13:15 UTC, phracek approved these changes
LGTM

2022-02-01 13:52 UTC, phracek commented
@sreber84 Please rebase this pull request including `common` submodule, so we can merge it.

2022-03-16 09:53 UTC, phracek commented on 2.4/root/usr/share/container-scripts/httpd/common.sh
> +  [ -d "$custom_dir" ] && find "$custom_dir" -maxdepth 5 -type f -name "$files_matched" -printf "%p\n"
@sreber84 Any update so we can merge it?

2022-03-16 09:54 UTC, phracek commented
[test-all]

2022-03-16 09:55 UTC, phracek commented on 2.4/root/usr/share/container-scripts/httpd/common.sh
> +  [ -d "$custom_dir" ] && find "$custom_dir" -maxdepth 5 -type f -name "$files_matched" -printf "%p\n"
@sreber84 How can I validate, that your change works well?

2022-03-28 18:46 UTC, closed without merging