make all test/run files only symlinks to one standard file
sclorg/httpd-container pull request #178
Opened 2023-05-09 06:36 UTC by zmiklank

The run file for micro image was out-of-date and I do not see reason why it should be separated from test/run anyway.

2023-05-09 06:41 UTC, zmiklank commented
[test]

2023-05-16 08:46 UTC, phracek commented
It would be nice to have everything in one commit. It is hard to review it.

2023-05-16 08:49 UTC, phracek requested changes
Please have a look at my comments. I would also prefer to get rid of `run` function. It is wrapper over run_command.

2023-05-16 08:49 UTC, phracek commented on test/run
> +TEST_LIST="\
This should be at the beginning of the file, as we have it in all other containers.

2023-05-16 08:49 UTC, phracek commented on test/run
> +test $# -eq 1 -a "${1-}" == --list && echo "$TEST_LIST" && exit 0
What is a reason for this? I don't follow.

2023-05-16 10:20 UTC, zmiklank commented
> It would be nice to have everything in one commit. It is hard to review it.

It is in one commit.

> Please have a look at my comments.

I did not change the contents of `test/run` file. Everything you see here was already present in the file. I only moved the file to different folder and created symlink to it. Do you want me to change it according you comments anyway?

2023-05-17 06:45 UTC, phracek commented
CentOS Stream 9 - 2.4-micro failed for this reason:

```bash
Running transaction test
RPM: error: Unable to change root directory: Operation not permitted
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  Errors occurred during test transaction.
```

I don't remember what was root case.

2023-05-17 07:02 UTC, zmiklank commented
I think it can be related to change of default capabilities in podman. Fix is here: https://github.com/sclorg/container-common-scripts/pull/339.

2023-05-17 10:15 UTC, phracek commented
The pull request https://github.com/sclorg/container-common-scripts/pull/339 is merged. Let's make changes here.

2023-05-18 06:24 UTC, zmiklank commented
[test]

2023-05-18 06:50 UTC, zmiklank commented
The needed changes were added.

2023-05-18 12:56 UTC, merged